import type { ProductSeed } from "./types";

export const categories = [
  { name: "Electronics", slug: "electronics", imageKey: "headphones" },
  { name: "Mobiles", slug: "mobiles", imageKey: "smartphone" },
  { name: "Fashion", slug: "fashion", imageKey: "shoes" },
  { name: "Home & Kitchen", slug: "home-kitchen", imageKey: "kitchen" },
  { name: "Books", slug: "books", imageKey: "book" },
  { name: "Beauty", slug: "beauty", imageKey: "makeup" },
  { name: "Sports", slug: "sports", imageKey: "gym" },
  { name: "Toys & Games", slug: "toys-games", imageKey: "toys" },
  { name: "Grocery", slug: "grocery", imageKey: "grocery" },
  { name: "Gaming", slug: "gaming", imageKey: "ps5" },
] as const;

export const productsByCategory: Record<string, ProductSeed[]> = {
  Electronics: [
    {
      name: "Sony WH-1000XM5 Wireless Headphones",
      brand: "Sony",
      price: 24990,
      compareAtPrice: 34990,
      stock: 45,
      featured: true,
      bestseller: true,
      rating: 4.7,
      reviewCount: 12847,
      imageKey: "headphones",
      highlights: ["Industry-leading ANC", "30-hour battery", "Multipoint Bluetooth 5.2"],
      specs: [["Driver Size", "30mm"], ["Battery Life", "30 hours"], ["Connectivity", "Bluetooth 5.2"], ["Noise Cancellation", "Adaptive ANC"], ["Weight", "250g"]],
    },
    {
      name: "LG 43-inch 4K Ultra HD Smart LED TV",
      brand: "LG",
      price: 32999,
      compareAtPrice: 45999,
      stock: 30,
      featured: true,
      rating: 4.5,
      reviewCount: 5621,
      imageKey: "tv",
      highlights: ["webOS smart TV", "4K upscaling", "Game Optimizer mode"],
      specs: [["Resolution", "4K Ultra HD"], ["Screen Size", "43 inches"], ["HDR", "HLG"], ["OS", "webOS 23"], ["Ports", "3x HDMI, 2x USB"]],
    },
    {
      name: "Samsung 55-inch Crystal UHD 4K Smart TV",
      brand: "Samsung",
      price: 54990,
      compareAtPrice: 74990,
      stock: 20,
      featured: true,
      bestseller: true,
      rating: 4.6,
      reviewCount: 8934,
      imageKey: "tvLarge",
      highlights: ["HDR10+ support", "Tizen smart hub", "Alexa built-in"],
      specs: [["Resolution", "4K UHD"], ["Screen Size", "55 inches"], ["HDR", "HDR10+"], ["OS", "Tizen"], ["Refresh Rate", "60Hz"]],
    },
    {
      name: "boAt Airdopes 141 Bluetooth TWS Earbuds",
      brand: "boAt",
      price: 1299,
      compareAtPrice: 3499,
      stock: 200,
      rating: 4.1,
      reviewCount: 156789,
      imageKey: "earbuds",
      highlights: ["42-hour total playback", "ENx call clarity", "IPX4 sweat resistance"],
      specs: [["Driver Size", "8mm"], ["Battery Life", "42 hours (case)"], ["Connectivity", "Bluetooth 5.0"], ["Water Resistance", "IPX4"], ["Charging", "Type-C"]],
    },
    {
      name: "JBL Flip 6 Portable Bluetooth Speaker",
      brand: "JBL",
      price: 9999,
      compareAtPrice: 13999,
      stock: 35,
      featured: true,
      rating: 4.6,
      reviewCount: 23456,
      imageKey: "speaker",
      highlights: ["IP67 waterproof", "12-hour playtime", "PartyBoost stereo pair"],
      specs: [["Output Power", "30W"], ["Battery Life", "12 hours"], ["Waterproof", "IP67"], ["Connectivity", "Bluetooth 5.1"], ["Weight", "550g"]],
    },
    {
      name: "Canon EOS 1500D DSLR Camera (24.1MP)",
      brand: "Canon",
      price: 34995,
      compareAtPrice: 44995,
      stock: 15,
      featured: true,
      rating: 4.5,
      reviewCount: 6782,
      imageKey: "camera",
      highlights: ["APS-C sensor", "Full HD video", "Wi-Fi image transfer"],
      specs: [["Megapixels", "24.1MP"], ["Sensor", "APS-C CMOS"], ["ISO Range", "100-6400"], ["Video", "Full HD 1080p"], ["Connectivity", "Wi-Fi, NFC"]],
    },
    {
      name: "HP Pavilion 15 Laptop (Intel i5, 16GB)",
      brand: "HP",
      price: 58990,
      compareAtPrice: 72990,
      stock: 25,
      featured: true,
      bestseller: true,
      rating: 4.4,
      reviewCount: 3421,
      imageKey: "laptop",
      highlights: ["16GB RAM upgrade", "512GB PCIe SSD", "FHD micro-edge display"],
      specs: [["Processor", "Intel Core i5-1335U"], ["RAM", "16GB DDR4"], ["Storage", "512GB SSD"], ["Display", "15.6 FHD IPS"], ["OS", "Windows 11 Home"]],
    },
    {
      name: "Dell Inspiron 15 Laptop (Ryzen 5, 8GB)",
      brand: "Dell",
      price: 45990,
      compareAtPrice: 59990,
      stock: 22,
      rating: 4.3,
      reviewCount: 2890,
      imageKey: "laptop",
      highlights: ["AMD Ryzen efficiency", "ComfortView display", "ExpressCharge"],
      specs: [["Processor", "AMD Ryzen 5 7520U"], ["RAM", "8GB DDR4"], ["Storage", "512GB SSD"], ["Display", "15.6 FHD"], ["OS", "Windows 11 Home"]],
    },
    {
      name: "Asus VA24EHF 24-inch IPS Monitor",
      brand: "Asus",
      price: 8999,
      compareAtPrice: 12999,
      stock: 40,
      rating: 4.4,
      reviewCount: 4512,
      imageKey: "monitor",
      highlights: ["75Hz smooth refresh", "IPS wide viewing angles", "Low Blue Light mode"],
      specs: [["Panel", "23.8-inch IPS"], ["Resolution", "1920 x 1080"], ["Refresh Rate", "75Hz"], ["Response Time", "1ms MPRT"], ["Ports", "HDMI, VGA"]],
    },
    {
      name: "Boat Wave Call Smartwatch",
      brand: "boAt",
      price: 1999,
      compareAtPrice: 4999,
      stock: 120,
      rating: 4.0,
      reviewCount: 98234,
      imageKey: "smartwatch",
      highlights: ["Bluetooth calling", "100+ watch faces", "7-day battery"],
      specs: [["Display", "1.69-inch HD"], ["Battery Life", "7 days"], ["Water Resistance", "IP68"], ["Sensors", "HR, SpO2"], ["Compatibility", "Android & iOS"]],
    },
    {
      name: "Apple iPad Air 11-inch (M2, Wi-Fi)",
      brand: "Apple",
      price: 59900,
      compareAtPrice: 69900,
      stock: 18,
      featured: true,
      bestseller: true,
      rating: 4.8,
      reviewCount: 12456,
      imageKey: "tablet",
      createdAt: new Date("2099-01-01T00:00:00.000Z"),
      highlights: ["M2 chip performance", "Liquid Retina display", "All-day battery"],
      specs: [["Processor", "Apple M2"], ["Storage", "128GB"], ["Display", "11-inch Liquid Retina"], ["Connectivity", "Wi-Fi"], ["Battery", "Up to 10 hours"]],
    },
    {
      name: "Lenovo Yoga Slim 7i OLED Laptop",
      brand: "Lenovo",
      price: 74990,
      compareAtPrice: 89990,
      stock: 16,
      featured: true,
      rating: 4.6,
      reviewCount: 7342,
      imageKey: "laptopAlt",
      createdAt: new Date("2099-01-01T00:00:00.000Z"),
      highlights: ["Intel Evo platform", "2.8K OLED display", "Ultra-light metal build"],
      specs: [["Processor", "Intel Core Ultra 5"], ["RAM", "16GB"], ["Storage", "512GB SSD"], ["Display", "14-inch OLED"], ["Weight", "1.4kg"]],
    },
    {
      name: "ASUS ROG Azoth Mechanical Keyboard",
      brand: "ASUS",
      price: 19990,
      compareAtPrice: 22990,
      stock: 24,
      featured: true,
      rating: 4.7,
      reviewCount: 4521,
      imageKey: "keyboardAlt",
      createdAt: new Date("2099-01-01T00:00:00.000Z"),
      highlights: ["Hot-swappable switches", "OLED display", "Tri-mode connectivity"],
      specs: [["Switch Type", "Mechanical"], ["Connectivity", "Bluetooth/2.4GHz/USB"], ["Battery", "Up to 2000 hours"], ["Layout", "75% compact"], ["Backlight", "RGB"]],
    },
    {
      name: "Sony Alpha ZV-E10 Camera",
      brand: "Sony",
      price: 65990,
      compareAtPrice: 76990,
      stock: 12,
      featured: true,
      rating: 4.7,
      reviewCount: 8821,
      imageKey: "cameraAlt",
      createdAt: new Date("2099-01-01T00:00:00.000Z"),
      highlights: ["APS-C sensor", "Product showcase mode", "4K video recording"],
      specs: [["Sensor", "24.2MP APS-C"], ["Video", "4K 30fps"], ["Lens Mount", "E-mount"], ["Connectivity", "Wi-Fi, Bluetooth"], ["Weight", "343g"]],
    },
    {
      name: "JBL Charge 5 Portable Bluetooth Speaker",
      brand: "JBL",
      price: 12999,
      compareAtPrice: 15999,
      stock: 30,
      featured: true,
      rating: 4.6,
      reviewCount: 19334,
      imageKey: "speakerAlt",
      createdAt: new Date("2099-01-01T00:00:00.000Z"),
      highlights: ["20-hour battery", "IP67 waterproof", "Powerbank output"],
      specs: [["Output Power", "40W"], ["Battery Life", "20 hours"], ["Waterproof", "IP67"], ["Connectivity", "Bluetooth 5.1"], ["Weight", "960g"]],
    },
    {
      name: "Samsung Galaxy Watch6 Classic",
      brand: "Samsung",
      price: 29999,
      compareAtPrice: 34999,
      stock: 27,
      featured: true,
      rating: 4.5,
      reviewCount: 11567,
      imageKey: "watchAlt",
      createdAt: new Date("2099-01-01T00:00:00.000Z"),
      highlights: ["Rotating bezel", "Sleep coaching", "Body composition analysis"],
      specs: [["Display", "1.5-inch Super AMOLED"], ["Battery", "Up to 40 hours"], ["Water Resistance", "5ATM"], ["Connectivity", "Bluetooth, Wi-Fi"], ["Sensors", "HR, ECG, SpO2"]],
    },
  ],

  Mobiles: [
    {
      name: "Apple iPhone 15 (128GB)",
      brand: "Apple",
      price: 79900,
      compareAtPrice: 89900,
      stock: 50,
      featured: true,
      bestseller: true,
      rating: 4.7,
      reviewCount: 24561,
      imageKey: "smartphone",
      highlights: ["A16 Bionic chip", "48MP main camera", "USB-C charging"],
      specs: [["Processor", "Apple A16 Bionic"], ["RAM", "6GB"], ["Storage", "128GB"], ["Display", "6.1 Super Retina XDR"], ["Camera", "48MP + 12MP Ultra Wide"]],
    },
    {
      name: "Samsung Galaxy S24 5G (256GB)",
      brand: "Samsung",
      price: 74999,
      compareAtPrice: 84999,
      stock: 40,
      featured: true,
      bestseller: true,
      rating: 4.6,
      reviewCount: 18924,
      imageKey: "smartphoneAlt",
      highlights: ["Galaxy AI features", "120Hz AMOLED", "7 years OS updates"],
      specs: [["Processor", "Snapdragon 8 Gen 3"], ["RAM", "8GB"], ["Storage", "256GB"], ["Display", "6.2 FHD+ AMOLED 120Hz"], ["Camera", "50MP Triple Camera"]],
    },
    {
      name: "OnePlus 12R 5G (8GB/128GB)",
      brand: "OnePlus",
      price: 39999,
      compareAtPrice: 44999,
      stock: 60,
      rating: 4.4,
      reviewCount: 11234,
      imageKey: "smartphoneAlt2",
      highlights: ["100W SUPERVOOC", "5500mAh battery", "Alert Slider"],
      specs: [["Processor", "Snapdragon 8 Gen 2"], ["RAM", "8GB"], ["Storage", "128GB"], ["Display", "6.78 AMOLED 120Hz"], ["Battery", "5500mAh"]],
    },
    {
      name: "Xiaomi Redmi Note 13 Pro 5G",
      brand: "Xiaomi",
      price: 26999,
      compareAtPrice: 32999,
      stock: 85,
      featured: true,
      rating: 4.4,
      reviewCount: 28456,
      imageKey: "smartphone",
      highlights: ["200MP OIS camera", "67W fast charging", "IP54 rating"],
      specs: [["Processor", "Dimensity 7200 Ultra"], ["RAM", "8GB"], ["Storage", "256GB"], ["Display", "6.67 AMOLED 120Hz"], ["Camera", "200MP Main"]],
    },
    {
      name: "Realme 12 Pro+ 5G",
      brand: "Realme",
      price: 29999,
      compareAtPrice: 35999,
      stock: 55,
      featured: true,
      rating: 4.2,
      reviewCount: 9876,
      imageKey: "smartphoneAlt",
      highlights: ["Periscope telephoto", "120Hz curved display", "67W charge"],
      specs: [["Processor", "Snapdragon 7s Gen 2"], ["RAM", "8GB"], ["Storage", "256GB"], ["Display", "6.7 AMOLED 120Hz"], ["Camera", "50MP Periscope"]],
    },
    {
      name: "Vivo V30 5G",
      brand: "Vivo",
      price: 34999,
      compareAtPrice: 39999,
      stock: 45,
      rating: 4.1,
      reviewCount: 7654,
      imageKey: "smartphoneAlt2",
      highlights: ["ZEISS portrait optics", "Aura light portrait", "80W flash charge"],
      specs: [["Processor", "Snapdragon 7 Gen 3"], ["RAM", "8GB"], ["Storage", "256GB"], ["Display", "6.78 AMOLED 120Hz"], ["Camera", "50MP ZEISS"]],
    },
    {
      name: "Oppo Reno 12 5G",
      brand: "Oppo",
      price: 31999,
      compareAtPrice: 37999,
      stock: 48,
      rating: 4.2,
      reviewCount: 5432,
      imageKey: "smartphone",
      highlights: ["AI Portrait Expert", "80W SUPERVOOC", "Slim 7.6mm design"],
      specs: [["Processor", "Dimensity 7300"], ["RAM", "8GB"], ["Storage", "256GB"], ["Display", "6.7 AMOLED 120Hz"], ["Camera", "50MP Sony LYT"]],
    },
    {
      name: "iQOO Neo 9 Pro 5G",
      brand: "iQOO",
      price: 36999,
      compareAtPrice: 42999,
      stock: 40,
      rating: 4.3,
      reviewCount: 6789,
      imageKey: "smartphoneAlt",
      highlights: ["144Hz gaming display", "120W fast charging", "Vapor cooling"],
      specs: [["Processor", "Snapdragon 8 Gen 2"], ["RAM", "8GB"], ["Storage", "128GB"], ["Display", "6.78 AMOLED 144Hz"], ["Battery", "5160mAh"]],
    },
    {
      name: "Samsung 25W Super Fast Charger",
      brand: "Samsung",
      price: 1499,
      compareAtPrice: 2499,
      stock: 180,
      rating: 4.5,
      reviewCount: 45678,
      imageKey: "accessory",
      highlights: ["PPS fast charging", "Compact travel design", "USB-C cable included"],
      specs: [["Output", "25W PPS"], ["Port", "USB Type-C"], ["Compatibility", "Samsung & USB-PD devices"], ["Cable Length", "1m"], ["Warranty", "6 Months"]],
    },
    {
      name: "Spigen Ultra Hybrid Back Cover (Universal)",
      brand: "Spigen",
      price: 899,
      compareAtPrice: 1499,
      stock: 250,
      rating: 4.4,
      reviewCount: 32145,
      imageKey: "accessory",
      highlights: ["Military-grade protection", "Crystal clear back", "Raised lip for camera"],
      specs: [["Material", "TPU + Polycarbonate"], ["Protection", "Drop tested"], ["Fit", "Snug precision cutouts"], ["Wireless Charging", "Compatible"], ["Weight", "28g"]],
    },
  ],

  Fashion: [
    {
      name: "Nike Revolution 6 Running Shoes",
      brand: "Nike",
      price: 3995,
      compareAtPrice: 4995,
      stock: 70,
      featured: true,
      bestseller: true,
      rating: 4.5,
      reviewCount: 18234,
      imageKey: "shoes",
      highlights: ["Soft foam midsole", "Breathable mesh upper", "Everyday road running"],
      specs: [["Upper", "Mesh"], ["Sole", "Rubber"], ["Closure", "Lace-Up"], ["Use", "Road Running"], ["Sizes", "UK 6-11"]],
    },
    {
      name: "Adidas Ultraboost Light Shoes",
      brand: "Adidas",
      price: 8999,
      compareAtPrice: 15999,
      stock: 45,
      featured: true,
      rating: 4.4,
      reviewCount: 7654,
      imageKey: "shoes",
      highlights: ["Light BOOST cushioning", "Continental rubber outsole", "Primeknit upper"],
      specs: [["Midsole", "BOOST Light"], ["Outsole", "Continental Rubber"], ["Upper", "Primeknit"], ["Drop", "10mm"], ["Weight", "260g"]],
    },
    {
      name: "Puma Softride Premier Running Shoes",
      brand: "Puma",
      price: 2999,
      compareAtPrice: 4999,
      stock: 65,
      rating: 4.3,
      reviewCount: 9876,
      imageKey: "shoes",
      highlights: ["SOFTRIDE foam", "Lightweight daily trainer", "Bold Puma branding"],
      specs: [["Upper", "Mesh"], ["Sole", "Rubber"], ["Technology", "SOFTRIDE"], ["Closure", "Lace-Up"], ["Weight", "280g"]],
    },
    {
      name: "Levis 511 Slim Fit Jeans",
      brand: "Levi's",
      price: 2499,
      compareAtPrice: 3499,
      stock: 90,
      featured: true,
      rating: 4.4,
      reviewCount: 12345,
      imageKey: "jeans",
      highlights: ["Classic 5-pocket styling", "Slim through hip and thigh", "Durable denim weave"],
      specs: [["Material", "99% Cotton 1% Elastane"], ["Fit", "Slim"], ["Rise", "Mid Rise"], ["Wash", "Medium Indigo"], ["Sizes", "28-38"]],
    },
    {
      name: "Allen Solly Men's Formal Shirt",
      brand: "Allen Solly",
      price: 1299,
      compareAtPrice: 1999,
      stock: 80,
      rating: 4.2,
      reviewCount: 8765,
      imageKey: "shirt",
      highlights: ["Wrinkle-resistant fabric", "Spread collar", "Office-ready fit"],
      specs: [["Material", "Cotton Blend"], ["Fit", "Regular"], ["Collar", "Spread"], ["Pattern", "Solid"], ["Care", "Machine Wash"]],
    },
    {
      name: "H&M Regular Fit Cotton T-Shirt",
      brand: "H&M",
      price: 599,
      compareAtPrice: 999,
      stock: 200,
      rating: 4.1,
      reviewCount: 23456,
      imageKey: "shirt",
      highlights: ["Soft organic cotton", "Crew neck", "Everyday basics"],
      specs: [["Material", "100% Cotton"], ["Fit", "Regular"], ["Neck", "Crew Neck"], ["Sleeve", "Short"], ["Sizes", "XS-XXL"]],
    },
    {
      name: "Fabindia Handloom Cotton Kurta",
      brand: "Fabindia",
      price: 1599,
      compareAtPrice: 2499,
      stock: 55,
      rating: 4.3,
      reviewCount: 4321,
      imageKey: "ethnic",
      highlights: ["Handloom weave", "Festive ethnic wear", "Breathable cotton"],
      specs: [["Material", "Handloom Cotton"], ["Fit", "Regular"], ["Sleeve", "3/4 Sleeve"], ["Occasion", "Festive & Casual"], ["Care", "Gentle Wash"]],
    },
    {
      name: "Fastrack Reflex Active Smartwatch",
      brand: "Fastrack",
      price: 1995,
      compareAtPrice: 3495,
      stock: 85,
      rating: 4.0,
      reviewCount: 15678,
      imageKey: "smartwatch",
      highlights: ["1.69-inch display", "SpO2 & sleep tracking", "5 ATM water resistance"],
      specs: [["Display", "1.69-inch"], ["Battery", "Up to 7 days"], ["Water Resistance", "5 ATM"], ["Strap", "Silicone"], ["Compatibility", "Android & iOS"]],
    },
    {
      name: "Lavie Women's Handbag",
      brand: "Lavie",
      price: 1499,
      compareAtPrice: 2999,
      stock: 60,
      rating: 4.2,
      reviewCount: 6789,
      imageKey: "handbag",
      highlights: ["Structured silhouette", "Multiple compartments", "Adjustable strap"],
      specs: [["Material", "Faux Leather"], ["Closure", "Zip"], ["Compartments", "3"], ["Strap", "Adjustable"], ["Dimensions", "28 x 12 x 22 cm"]],
    },
  ],

  "Home & Kitchen": [
    {
      name: "Prestige Svachh 5L Pressure Cooker",
      brand: "Prestige",
      price: 1899,
      compareAtPrice: 2799,
      stock: 70,
      featured: true,
      rating: 4.4,
      reviewCount: 34521,
      imageKey: "kitchen",
      highlights: ["5-year warranty", "Spillage control lid", "ISI certified"],
      specs: [["Capacity", "5 Litres"], ["Material", "Hard Anodised"], ["Base", "Induction compatible"], ["Warranty", "5 Years"], ["Safety", "ISI Marked"]],
    },
    {
      name: "Philips HD9252 Air Fryer 4.1L",
      brand: "Philips",
      price: 5499,
      compareAtPrice: 8999,
      stock: 40,
      featured: true,
      bestseller: true,
      rating: 4.5,
      reviewCount: 23156,
      imageKey: "appliance",
      highlights: ["Rapid Air technology", "90% less oil cooking", "Touch panel presets"],
      specs: [["Capacity", "4.1 Litres"], ["Power", "1400W"], ["Temperature", "80-200°C"], ["Preset Menus", "7"], ["Warranty", "2 Years"]],
    },
    {
      name: "Milton Thermosteel Flask 1L",
      brand: "Milton",
      price: 799,
      compareAtPrice: 1299,
      stock: 150,
      rating: 4.3,
      reviewCount: 45678,
      imageKey: "kitchen",
      highlights: ["24-hour heat retention", "Leak-proof lid", "304 stainless steel"],
      specs: [["Capacity", "1 Litre"], ["Material", "Stainless Steel 304"], ["Insulation", "18-24 Hours"], ["Leak Proof", "Yes"], ["BPA Free", "Yes"]],
    },
    {
      name: "Pigeon Aluminium Non-Stick Kadai 24cm",
      brand: "Pigeon",
      price: 699,
      compareAtPrice: 1299,
      stock: 100,
      rating: 4.0,
      reviewCount: 12345,
      imageKey: "kitchen",
      highlights: ["Non-stick coating", "Bakelite handle", "Even heat distribution"],
      specs: [["Diameter", "24cm"], ["Material", "Aluminium"], ["Coating", "Non-Stick"], ["Handle", "Bakelite"], ["Gas Stove", "Compatible"]],
    },
    {
      name: "Bajaj 750W Mixer Grinder",
      brand: "Bajaj",
      price: 2099,
      compareAtPrice: 3299,
      stock: 55,
      rating: 4.2,
      reviewCount: 18234,
      imageKey: "appliance",
      highlights: ["750W powerful motor", "3 stainless jars", "5-year motor warranty"],
      specs: [["Power", "750W"], ["Jars", "3"], ["Speed", "3 + Pulse"], ["Motor Warranty", "5 Years"], ["Overload Protection", "Yes"]],
    },
    {
      name: "Havells Pro Induction Cooktop 2000W",
      brand: "Havells",
      price: 3499,
      compareAtPrice: 4999,
      stock: 45,
      featured: true,
      rating: 4.3,
      reviewCount: 8765,
      imageKey: "appliance",
      highlights: ["8 preset menus", "Auto pan detection", "Child lock"],
      specs: [["Power", "2000W"], ["Presets", "8 Menus"], ["Timer", "180 min"], ["Safety", "Auto Shut Off"], ["Warranty", "2 Years"]],
    },
    {
      name: "Borosil Vision Glass Set (6 pcs)",
      brand: "Borosil",
      price: 599,
      compareAtPrice: 999,
      stock: 200,
      rating: 4.5,
      reviewCount: 23456,
      imageKey: "kitchen",
      highlights: ["Borosilicate glass", "Microwave safe", "Dishwasher safe"],
      specs: [["Pieces", "6 Glasses"], ["Capacity", "200ml each"], ["Material", "Borosilicate"], ["Microwave Safe", "Yes"], ["Dishwasher Safe", "Yes"]],
    },
    {
      name: "Cello Ultra Stainless Steel Casserole 3.5L",
      brand: "Cello",
      price: 1299,
      compareAtPrice: 2199,
      stock: 80,
      rating: 4.1,
      reviewCount: 5678,
      imageKey: "kitchen",
      highlights: ["Hot/cold retention", "Stackable design", "BPA-free inner"],
      specs: [["Capacity", "3.5 Litres"], ["Material", "Stainless Steel"], ["Insulation", "4-6 Hours"], ["Lid", "Stainless Steel"], ["BPA Free", "Yes"]],
    },
    {
      name: "Eureka Forbes Aquaguard RO Water Purifier",
      brand: "Eureka Forbes",
      price: 11990,
      compareAtPrice: 15990,
      stock: 20,
      featured: true,
      rating: 4.4,
      reviewCount: 7890,
      imageKey: "appliance",
      highlights: ["RO+UV+MTDS purification", "7L storage", "Free installation"],
      specs: [["Technology", "RO+UV+MTDS"], ["Capacity", "7 Litres"], ["Purification Rate", "20L/hr"], ["Installation", "Wall Mount"], ["Warranty", "1 Year"]],
    },
  ],

  Books: [
    {
      name: "Atomic Habits by James Clear",
      brand: "Penguin",
      price: 399,
      compareAtPrice: 699,
      stock: 300,
      featured: true,
      bestseller: true,
      rating: 4.8,
      reviewCount: 89432,
      imageKey: "book",
      highlights: ["#1 NYT bestseller", "Practical habit systems", "Paperback edition"],
      specs: [["Author", "James Clear"], ["Pages", "320"], ["Format", "Paperback"], ["Language", "English"], ["Genre", "Self-Help"]],
    },
    {
      name: "Clean Code by Robert C. Martin",
      brand: "Prentice Hall",
      price: 899,
      compareAtPrice: 1299,
      stock: 120,
      featured: true,
      rating: 4.7,
      reviewCount: 12456,
      imageKey: "bookAlt",
      highlights: ["Essential for developers", "Refactoring practices", "Agile craftsmanship"],
      specs: [["Author", "Robert C. Martin"], ["Pages", "464"], ["Format", "Paperback"], ["Language", "English"], ["Genre", "Programming"]],
    },
    {
      name: "The Psychology of Money by Morgan Housel",
      brand: "Jaico",
      price: 349,
      compareAtPrice: 599,
      stock: 250,
      featured: true,
      rating: 4.7,
      reviewCount: 56789,
      imageKey: "book",
      highlights: ["Timeless money lessons", "Short insightful chapters", "Indian finance context"],
      specs: [["Author", "Morgan Housel"], ["Pages", "256"], ["Format", "Paperback"], ["Language", "English"], ["Genre", "Finance"]],
    },
    {
      name: "Sapiens by Yuval Noah Harari",
      brand: "Vintage",
      price: 499,
      compareAtPrice: 799,
      stock: 180,
      featured: true,
      rating: 4.6,
      reviewCount: 34567,
      imageKey: "bookAlt",
      highlights: ["History of humankind", "Thought-provoking narrative", "International bestseller"],
      specs: [["Author", "Yuval Noah Harari"], ["Pages", "512"], ["Format", "Paperback"], ["Language", "English"], ["Genre", "Fiction / History"]],
    },
    {
      name: "Wings of Fire by APJ Abdul Kalam",
      brand: "Universities Press",
      price: 249,
      compareAtPrice: 449,
      stock: 350,
      featured: true,
      rating: 4.8,
      reviewCount: 67890,
      imageKey: "book",
      highlights: ["Indian icon biography", "Inspirational memoir", "Student favourite"],
      specs: [["Author", "APJ Abdul Kalam"], ["Pages", "196"], ["Format", "Paperback"], ["Language", "English"], ["Genre", "Autobiography"]],
    },
    {
      name: "The Alchemist by Paulo Coelho",
      brand: "HarperCollins",
      price: 299,
      compareAtPrice: 499,
      stock: 280,
      rating: 4.6,
      reviewCount: 45678,
      imageKey: "bookAlt",
      highlights: ["Modern classic fiction", "Philosophical journey", "Gift-worthy edition"],
      specs: [["Author", "Paulo Coelho"], ["Pages", "197"], ["Format", "Paperback"], ["Language", "English"], ["Genre", "Fiction"]],
    },
    {
      name: "Zero to One by Peter Thiel",
      brand: "Crown Business",
      price: 449,
      compareAtPrice: 799,
      stock: 160,
      rating: 4.5,
      reviewCount: 23456,
      imageKey: "book",
      highlights: ["Startup insights", "Monopoly thinking", "Silicon Valley lessons"],
      specs: [["Author", "Peter Thiel"], ["Pages", "224"], ["Format", "Paperback"], ["Language", "English"], ["Genre", "Business"]],
    },
    {
      name: "Deep Work by Cal Newport",
      brand: "Piatkus",
      price: 449,
      compareAtPrice: 699,
      stock: 140,
      rating: 4.5,
      reviewCount: 18901,
      imageKey: "bookAlt",
      highlights: ["Focus in distracted world", "Productivity frameworks", "Career growth"],
      specs: [["Author", "Cal Newport"], ["Pages", "304"], ["Format", "Paperback"], ["Language", "English"], ["Genre", "Productivity"]],
    },
    {
      name: "Rich Dad Poor Dad by Robert Kiyosaki",
      brand: "Plata Publishing",
      price: 399,
      compareAtPrice: 699,
      stock: 220,
      featured: true,
      rating: 4.6,
      reviewCount: 78901,
      imageKey: "book",
      highlights: ["Financial literacy classic", "Asset vs liability mindset", "Easy to read"],
      specs: [["Author", "Robert Kiyosaki"], ["Pages", "336"], ["Format", "Paperback"], ["Language", "English"], ["Genre", "Finance"]],
    },
  ],

  Beauty: [
    {
      name: "Mamaearth Vitamin C Daily Glow Serum",
      brand: "Mamaearth",
      price: 549,
      compareAtPrice: 899,
      stock: 200,
      featured: true,
      bestseller: true,
      rating: 4.3,
      reviewCount: 45231,
      imageKey: "skincare",
      highlights: ["Vitamin C + turmeric", "Made Safe certified", "Dermatologically tested"],
      specs: [["Volume", "30ml"], ["Skin Type", "All"], ["Key Ingredient", "Vitamin C"], ["Paraben Free", "Yes"], ["Cruelty Free", "Yes"]],
    },
    {
      name: "Lakme Absolute Matte Mousse Lipstick",
      brand: "Lakme",
      price: 699,
      compareAtPrice: 1099,
      stock: 180,
      rating: 4.2,
      reviewCount: 23456,
      imageKey: "makeup",
      highlights: ["16-hour matte wear", "Lightweight mousse", "36 shades"],
      specs: [["Finish", "Matte"], ["Wear Time", "16 Hours"], ["Formula", "Mousse"], ["Transfer Proof", "Yes"], ["Shades", "36"]],
    },
    {
      name: "Maybelline Fit Me Matte Foundation",
      brand: "Maybelline",
      price: 549,
      compareAtPrice: 799,
      stock: 160,
      featured: true,
      rating: 4.3,
      reviewCount: 34567,
      imageKey: "makeup",
      highlights: ["Oil-free formula", "Wide shade range", "Poreless finish"],
      specs: [["Volume", "30ml"], ["Finish", "Matte"], ["Coverage", "Medium"], ["SPF", "SPF 22"], ["Skin Type", "Normal to Oily"]],
    },
    {
      name: "Minimalist 10% Niacinamide Face Serum",
      brand: "Minimalist",
      price: 599,
      compareAtPrice: 899,
      stock: 190,
      featured: true,
      rating: 4.4,
      reviewCount: 28765,
      imageKey: "skincare",
      highlights: ["Acne & pore care", "Fragrance free", "Transparent formula"],
      specs: [["Volume", "30ml"], ["Active", "10% Niacinamide"], ["Fragrance", "None"], ["Skin Type", "Oily & Acne"], ["pH", "5.0-6.0"]],
    },
    {
      name: "LOreal Paris Extraordinary Oil Shampoo 640ml",
      brand: "L'Oreal",
      price: 449,
      compareAtPrice: 699,
      stock: 220,
      rating: 4.2,
      reviewCount: 19876,
      imageKey: "haircare",
      highlights: ["6 rare flower oils", "Frizz control", "Salon-soft hair"],
      specs: [["Volume", "640ml"], ["Hair Type", "Dry & Damaged"], ["Key Ingredient", "Flower Oils"], ["Sulfate Free", "No"], ["For", "Women"]],
    },
    {
      name: "Nivea Soft Light Moisturising Cream 300ml",
      brand: "Nivea",
      price: 349,
      compareAtPrice: 499,
      stock: 280,
      rating: 4.5,
      reviewCount: 56789,
      imageKey: "skincare",
      highlights: ["Jojoba oil & vitamin E", "Non-greasy", "Face & body use"],
      specs: [["Volume", "300ml"], ["Skin Type", "All"], ["Texture", "Light Cream"], ["Key Ingredient", "Jojoba Oil"], ["Dermatologically Tested", "Yes"]],
    },
    {
      name: "Himalaya Purifying Neem Face Wash 200ml",
      brand: "Himalaya",
      price: 199,
      compareAtPrice: 299,
      stock: 400,
      rating: 4.4,
      reviewCount: 78923,
      imageKey: "skincare",
      highlights: ["Neem & turmeric", "Soap-free herbal", "Oily skin friendly"],
      specs: [["Volume", "200ml"], ["Skin Type", "Oily"], ["Key Ingredient", "Neem"], ["Paraben Free", "Yes"], ["Soap Free", "Yes"]],
    },
    {
      name: "Plum BodyLovin Hawaiian Rumba EDP 50ml",
      brand: "Plum",
      price: 895,
      compareAtPrice: 1295,
      stock: 90,
      featured: true,
      rating: 4.1,
      reviewCount: 6543,
      imageKey: "perfume",
      highlights: ["Tropical fruity notes", "Vegan & cruelty free", "Long-lasting EDP"],
      specs: [["Volume", "50ml"], ["Type", "Eau de Parfum"], ["Notes", "Fruity Floral"], ["Vegan", "Yes"], ["Gender", "Women"]],
    },
    {
      name: "Lakme 9 to 5 Eyeconic Kajal",
      brand: "Lakme",
      price: 210,
      compareAtPrice: 350,
      stock: 350,
      rating: 4.3,
      reviewCount: 45678,
      imageKey: "makeup",
      highlights: ["Smudge-proof", "Deep black pigment", "Twist-up format"],
      specs: [["Weight", "0.35g"], ["Finish", "Matte Black"], ["Smudge Proof", "Up to 10 hours"], ["Ophthalmologist Tested", "Yes"], ["Format", "Pencil Kajal"]],
    },
  ],

  Sports: [
    {
      name: "Yonex GR 303 Badminton Racket",
      brand: "Yonex",
      price: 599,
      compareAtPrice: 999,
      stock: 120,
      rating: 4.2,
      reviewCount: 8934,
      imageKey: "badminton",
      highlights: ["Isometric head shape", "Beginner friendly", "Durable steel shaft"],
      specs: [["Weight", "U"], ["Balance", "Even"], ["Grip", "G4"], ["Material", "Steel"], ["Level", "Beginner"]],
    },
    {
      name: "Cosco Hurricane Cricket Bat (Kashmir Willow)",
      brand: "Cosco",
      price: 1299,
      compareAtPrice: 2499,
      stock: 80,
      rating: 4.0,
      reviewCount: 5678,
      imageKey: "cricket",
      highlights: ["Full size bat", "Cane handle", "Tennis ball cricket"],
      specs: [["Size", "Full Size"], ["Willow", "Kashmir"], ["Weight", "1.1-1.2 kg"], ["Handle", "Cane"], ["Use", "Tennis Ball"]],
    },
    {
      name: "Nivia Storm Football Size 5",
      brand: "Nivia",
      price: 799,
      compareAtPrice: 1499,
      stock: 100,
      rating: 4.1,
      reviewCount: 4321,
      imageKey: "football",
      highlights: ["FIFA inspected size 5", "32-panel design", "Match play ready"],
      specs: [["Size", "5"], ["Material", "PU"], ["Bladder", "Butyl"], ["Use", "Match Play"], ["Colour", "White/Black"]],
    },
    {
      name: "Adidas Tiro League Football Shoes",
      brand: "Adidas",
      price: 3499,
      compareAtPrice: 4999,
      stock: 55,
      featured: true,
      rating: 4.4,
      reviewCount: 3456,
      imageKey: "football",
      highlights: ["Firm ground studs", "Synthetic upper", "Classic 3-stripes"],
      specs: [["Surface", "Firm Ground"], ["Upper", "Synthetic"], ["Closure", "Lace-Up"], ["Sizes", "UK 6-11"], ["Use", "Football"]],
    },
    {
      name: "Nike Brasilia Training Duffel Bag",
      brand: "Nike",
      price: 2499,
      compareAtPrice: 3999,
      stock: 70,
      rating: 4.3,
      reviewCount: 6789,
      imageKey: "gym",
      highlights: ["Ventilated shoe compartment", "Water-resistant base", "Adjustable strap"],
      specs: [["Capacity", "60L"], ["Material", "Polyester"], ["Compartments", "Main + Shoe"], ["Strap", "Adjustable"], ["Use", "Gym & Travel"]],
    },
    {
      name: "Strauss Yoga Mat 6mm TPE",
      brand: "Strauss",
      price: 599,
      compareAtPrice: 1199,
      stock: 150,
      rating: 4.3,
      reviewCount: 12345,
      imageKey: "fitness",
      highlights: ["Eco-friendly TPE", "Non-slip texture", "Carry strap included"],
      specs: [["Thickness", "6mm"], ["Material", "TPE"], ["Size", "183 x 61 cm"], ["Non-Slip", "Yes"], ["Weight", "900g"]],
    },
    {
      name: "Kore 20kg Adjustable Dumbbell Set",
      brand: "Kore",
      price: 3499,
      compareAtPrice: 5999,
      stock: 30,
      featured: true,
      rating: 4.4,
      reviewCount: 2345,
      imageKey: "gym",
      highlights: ["Rubber coated plates", "Knurled grip", "Home gym starter"],
      specs: [["Weight", "20kg total"], ["Material", "Cast Iron"], ["Coating", "Rubber"], ["Set", "2 bars + plates"], ["Use", "Strength Training"]],
    },
    {
      name: "Cosco CB-120 Badminton Shuttlecock (Pack of 6)",
      brand: "Cosco",
      price: 349,
      compareAtPrice: 599,
      stock: 200,
      rating: 4.1,
      reviewCount: 8765,
      imageKey: "badminton",
      highlights: ["Feather shuttlecocks", "Stable flight", "Tournament practice"],
      specs: [["Pack", "6 Shuttlecocks"], ["Type", "Feather"], ["Speed", "Medium"], ["Use", "Practice & Match"], ["Brand", "Cosco"]],
    },
    {
      name: "Nike Dri-FIT Men's Training T-Shirt",
      brand: "Nike",
      price: 1495,
      compareAtPrice: 2495,
      stock: 110,
      rating: 4.4,
      reviewCount: 15678,
      imageKey: "fitness",
      highlights: ["Sweat-wicking fabric", "Gym & run ready", "Regular fit"],
      specs: [["Material", "Polyester"], ["Technology", "Dri-FIT"], ["Fit", "Regular"], ["Sleeve", "Short"], ["Sizes", "S-XXL"]],
    },
  ],

  "Toys & Games": [
    {
      name: "LEGO Classic Large Creative Brick Box",
      brand: "LEGO",
      price: 3999,
      compareAtPrice: 5999,
      stock: 50,
      featured: true,
      rating: 4.8,
      reviewCount: 4521,
      imageKey: "toys",
      highlights: ["790 colourful bricks", "Storage box lid", "Ages 4+"],
      specs: [["Pieces", "790"], ["Age", "4+"], ["Theme", "Classic"], ["Storage", "Included"], ["Material", "ABS Plastic"]],
    },
    {
      name: "Hot Wheels 20 Car Gift Pack",
      brand: "Hot Wheels",
      price: 999,
      compareAtPrice: 1799,
      stock: 80,
      rating: 4.5,
      reviewCount: 6789,
      imageKey: "toys",
      highlights: ["Die-cast metal bodies", "1:64 scale", "Collector assortment"],
      specs: [["Cars", "20"], ["Scale", "1:64"], ["Material", "Die-Cast"], ["Age", "3+"], ["Theme", "Mixed"]],
    },
    {
      name: "Funskool Snakes and Ladders Board Game",
      brand: "Funskool",
      price: 199,
      compareAtPrice: 399,
      stock: 200,
      rating: 4.2,
      reviewCount: 12345,
      imageKey: "toys",
      highlights: ["Classic family game", "2-4 players", "Foldable board"],
      specs: [["Players", "2-4"], ["Age", "4+"], ["Includes", "Board, Dice, Tokens"], ["Language", "English"], ["Duration", "30 min"]],
    },
    {
      name: "Play-Doh 10 Colour Pack",
      brand: "Play-Doh",
      price: 799,
      compareAtPrice: 1299,
      stock: 120,
      rating: 4.6,
      reviewCount: 9876,
      imageKey: "toys",
      highlights: ["Non-toxic compound", "Creative modelling", "Ages 2+"],
      specs: [["Colours", "10"], ["Weight", "200g total"], ["Non-Toxic", "Yes"], ["Age", "2+"], ["Certification", "ASTM D-4236"]],
    },
    {
      name: "Barbie Dreamhouse Playset",
      brand: "Barbie",
      price: 4999,
      compareAtPrice: 7999,
      stock: 25,
      featured: true,
      rating: 4.7,
      reviewCount: 2345,
      imageKey: "toys",
      highlights: ["3 floors, 8 rooms", "70+ accessories", "Interactive features"],
      specs: [["Floors", "3"], ["Rooms", "8"], ["Accessories", "70+"], ["Age", "3+"], ["Doll Included", "No"]],
    },
    {
      name: "Nerf N-Strike Elite Disruptor",
      brand: "Nerf",
      price: 1799,
      compareAtPrice: 2999,
      stock: 70,
      rating: 4.3,
      reviewCount: 5432,
      imageKey: "toys",
      highlights: ["6-dart rotating drum", "27m range", "Indoor/outdoor play"],
      specs: [["Darts", "6 Included"], ["Range", "27 meters"], ["Age", "8+"], ["Mechanism", "Spring"], ["Ammo", "Elite Darts"]],
    },
    {
      name: "Skillofun Wooden Animal Puzzle 48 pcs",
      brand: "Skillofun",
      price: 499,
      compareAtPrice: 999,
      stock: 130,
      rating: 4.4,
      reviewCount: 3456,
      imageKey: "toys",
      highlights: ["Premium wood pieces", "Educational theme", "Motor skills"],
      specs: [["Pieces", "48"], ["Material", "Wood"], ["Age", "3+"], ["Theme", "Animals"], ["Educational", "Yes"]],
    },
    {
      name: "Funskool Monopoly India Edition",
      brand: "Funskool",
      price: 799,
      compareAtPrice: 1299,
      stock: 90,
      featured: true,
      rating: 4.4,
      reviewCount: 7890,
      imageKey: "toys",
      highlights: ["India-themed properties", "2-8 players", "Family game night"],
      specs: [["Players", "2-8"], ["Age", "8+"], ["Duration", "60-180 min"], ["Language", "English"], ["Edition", "India"]],
    },
    {
      name: "Choco Multicolour Building Blocks 100 pcs",
      brand: "Choco",
      price: 699,
      compareAtPrice: 1299,
      stock: 110,
      rating: 4.3,
      reviewCount: 4567,
      imageKey: "toys",
      highlights: ["BPA-free ABS", "8 bright colours", "STEM learning"],
      specs: [["Pieces", "100"], ["Material", "ABS"], ["Age", "2+"], ["BPA Free", "Yes"], ["Colours", "8"]],
    },
  ],

  Grocery: [
    {
      name: "Tata Salt Vacuum Evaporated 1kg",
      brand: "Tata",
      price: 22,
      compareAtPrice: 28,
      stock: 500,
      rating: 4.5,
      reviewCount: 89012,
      imageKey: "salt",
      highlights: ["Iodized for health", "Free flow crystals", "India's trusted salt"],
      specs: [["Weight", "1kg"], ["Type", "Iodized"], ["Origin", "India"], ["Shelf Life", "24 Months"], ["Pack", "Pouch"]],
    },
    {
      name: "Aashirvaad Superior MP Atta 10kg",
      brand: "Aashirvaad",
      price: 399,
      compareAtPrice: 499,
      stock: 200,
      featured: true,
      bestseller: true,
      rating: 4.6,
      reviewCount: 67890,
      imageKey: "atta",
      highlights: ["100% MP whole wheat", "Soft rotis", "Lock freshness pack"],
      specs: [["Weight", "10kg"], ["Type", "Whole Wheat Atta"], ["Protein", "9g/100g"], ["Shelf Life", "6 Months"], ["Pack", "HDPE"]],
    },
    {
      name: "Surf Excel Matic Top Load 2kg",
      brand: "Surf Excel",
      price: 499,
      compareAtPrice: 699,
      stock: 150,
      rating: 4.4,
      reviewCount: 45678,
      imageKey: "detergent",
      highlights: ["Tough stain removal", "Machine wash formula", "Fresh fragrance"],
      specs: [["Weight", "2kg"], ["Type", "Detergent Powder"], ["Use", "Top Load WM"], ["Fragrance", "Fresh"], ["Stain Removal", "100 Stains"]],
    },
    {
      name: "Real Activ Mixed Fruit Juice 1L",
      brand: "Real",
      price: 99,
      compareAtPrice: 149,
      stock: 300,
      rating: 4.2,
      reviewCount: 34567,
      imageKey: "juice",
      highlights: ["No added preservatives", "Fruit pulp blend", "Breakfast favourite"],
      specs: [["Volume", "1L"], ["Flavour", "Mixed Fruit"], ["Pulp", "Yes"], ["Preservatives", "None Added"], ["Shelf Life", "6 Months"]],
    },
    {
      name: "Maggi 2-Minute Masala Noodles 12 Pack",
      brand: "Maggi",
      price: 199,
      compareAtPrice: 299,
      stock: 400,
      featured: true,
      bestseller: true,
      rating: 4.7,
      reviewCount: 123456,
      imageKey: "noodles",
      highlights: ["Ready in 2 minutes", "Masala tastemaker", "Hostel staple"],
      specs: [["Pack", "12 x 70g"], ["Flavour", "Masala"], ["Cook Time", "2 min"], ["Veg", "Yes"], ["Shelf Life", "12 Months"]],
    },
    {
      name: "Amul Butter Pasteurized 500g",
      brand: "Amul",
      price: 269,
      compareAtPrice: 299,
      stock: 250,
      rating: 4.7,
      reviewCount: 98765,
      imageKey: "butter",
      highlights: ["Utterly butterly delicious", "80% milk fat", "Refrigerate after opening"],
      specs: [["Weight", "500g"], ["Type", "Salted Butter"], ["Fat", "Min 80%"], ["Storage", "Refrigerated"], ["Shelf Life", "9 Months"]],
    },
    {
      name: "Nescafe Classic Instant Coffee 200g",
      brand: "Nescafe",
      price: 449,
      compareAtPrice: 599,
      stock: 180,
      rating: 4.5,
      reviewCount: 56789,
      imageKey: "coffee",
      highlights: ["Rich aroma", "Quick dissolve", "Morning brew"],
      specs: [["Weight", "200g"], ["Type", "Instant Coffee"], ["Roast", "Medium"], ["Caffeine", "~60mg/cup"], ["Shelf Life", "24 Months"]],
    },
    {
      name: "Parle-G Gold Glucose Biscuits 1kg",
      brand: "Parle",
      price: 149,
      compareAtPrice: 199,
      stock: 600,
      rating: 4.6,
      reviewCount: 112345,
      imageKey: "biscuits",
      highlights: ["India's favourite biscuit", "Tea-time classic", "Energy snack"],
      specs: [["Weight", "1kg"], ["Type", "Glucose"], ["Veg", "Yes"], ["Shelf Life", "6 Months"], ["Pack", "Family Pack"]],
    },
    {
      name: "Fortune Refined Sunflower Oil 5L",
      brand: "Fortune",
      price: 699,
      compareAtPrice: 899,
      stock: 200,
      featured: true,
      rating: 4.3,
      reviewCount: 78901,
      imageKey: "oil",
      highlights: ["Light and neutral taste", "Cholesterol free", "PET jar"],
      specs: [["Volume", "5L"], ["Type", "Sunflower Oil"], ["Cholesterol", "Free"], ["Pack", "PET Bottle"], ["Shelf Life", "12 Months"]],
    },
  ],

  Gaming: [
    {
      name: "Sony PlayStation 5 Console (Disc Edition)",
      brand: "Sony",
      price: 49990,
      compareAtPrice: 54990,
      stock: 10,
      featured: true,
      bestseller: true,
      rating: 4.9,
      reviewCount: 2341,
      imageKey: "ps5",
      highlights: ["4K gaming at 120fps", "Ultra-fast SSD", "DualSense haptics"],
      specs: [["Storage", "825GB SSD"], ["GPU", "10.28 TFLOPS"], ["Resolution", "Up to 8K"], ["Ray Tracing", "Yes"], ["Edition", "Disc"]],
    },
    {
      name: "Microsoft Xbox Series S 512GB",
      brand: "Microsoft",
      price: 34990,
      compareAtPrice: 39990,
      stock: 15,
      featured: true,
      rating: 4.7,
      reviewCount: 1890,
      imageKey: "console",
      highlights: ["All-digital console", "120fps support", "Game Pass ready"],
      specs: [["Storage", "512GB SSD"], ["GPU", "4 TFLOPS"], ["Resolution", "Up to 4K"], ["Digital", "Yes"], ["Game Pass", "Compatible"]],
    },
    {
      name: "Logitech G304 Lightspeed Wireless Mouse",
      brand: "Logitech",
      price: 2499,
      compareAtPrice: 3995,
      stock: 80,
      featured: true,
      bestseller: true,
      rating: 4.6,
      reviewCount: 23456,
      imageKey: "gamingMouse",
      highlights: ["HERO 12K sensor", "250-hour battery", "6 programmable buttons"],
      specs: [["DPI", "200-12000"], ["Battery", "250 Hours"], ["Wireless", "2.4GHz"], ["Weight", "99g"], ["Buttons", "6"]],
    },
    {
      name: "Razer BlackWidow V3 Mechanical Keyboard",
      brand: "Razer",
      price: 8999,
      compareAtPrice: 12999,
      stock: 35,
      featured: true,
      rating: 4.5,
      reviewCount: 5678,
      imageKey: "gamingKeyboard",
      highlights: ["Razer Green switches", "Chroma RGB", "Doubleshot keycaps"],
      specs: [["Switch", "Razer Green"], ["Layout", "Full Size"], ["RGB", "Chroma"], ["Connectivity", "USB"], ["Anti-Ghosting", "Yes"]],
    },
    {
      name: "HyperX Cloud II Gaming Headset",
      brand: "HyperX",
      price: 7499,
      compareAtPrice: 9999,
      stock: 50,
      rating: 4.4,
      reviewCount: 12345,
      imageKey: "gamingHeadset",
      highlights: ["7.1 virtual surround", "Memory foam ear cushions", "Detachable mic"],
      specs: [["Driver", "53mm"], ["Surround", "7.1 Virtual"], ["Mic", "Detachable"], ["Compatibility", "PC, PS, Xbox"], ["Cable", "USB + 3.5mm"]],
    },
    {
      name: "Asus ROG Strix G16 Gaming Laptop",
      brand: "Asus",
      price: 124990,
      compareAtPrice: 144990,
      stock: 8,
      featured: true,
      rating: 4.6,
      reviewCount: 987,
      imageKey: "gamingLaptop",
      highlights: ["RTX 4060 graphics", "165Hz display", "ROG Intelligent Cooling"],
      specs: [["GPU", "NVIDIA RTX 4060"], ["CPU", "Intel i7-13650HX"], ["RAM", "16GB DDR5"], ["Storage", "512GB SSD"], ["Display", "16 FHD 165Hz"]],
    },
    {
      name: "Sony DualSense Wireless Controller",
      brand: "Sony",
      price: 5990,
      compareAtPrice: 6990,
      stock: 60,
      rating: 4.7,
      reviewCount: 8765,
      imageKey: "gamepad",
      highlights: ["Adaptive triggers", "Haptic feedback", "Built-in microphone"],
      specs: [["Connectivity", "Bluetooth/USB-C"], ["Battery", "Rechargeable"], ["Compatibility", "PS5, PC"], ["Audio", "3.5mm Jack"], ["Colour", "White"]],
    },
    {
      name: "Ant Esports 614 Gaming Chair",
      brand: "Ant Esports",
      price: 12999,
      compareAtPrice: 18999,
      stock: 20,
      rating: 4.3,
      reviewCount: 3456,
      imageKey: "gamingChair",
      highlights: ["180° recline", "3D armrests", "Lumbar pillow included"],
      specs: [["Material", "PU Leather"], ["Max Load", "150kg"], ["Recline", "90-180°"], ["Armrest", "3D Adjustable"], ["Wheels", "5 Casters"]],
    },
    {
      name: "EA Sports FC 24 PS5",
      brand: "EA Sports",
      price: 3499,
      compareAtPrice: 4999,
      stock: 60,
      rating: 4.2,
      reviewCount: 4567,
      imageKey: "console",
      highlights: ["HyperMotion V gameplay", "Ultimate Team", "Indian Super League"],
      specs: [["Platform", "PlayStation 5"], ["Genre", "Sports"], ["Players", "1-4"], ["Online", "Yes"], ["Rating", "3+"]],
    },
  ],
};

export const categorySlugByName: Record<string, string> = Object.fromEntries(
  categories.map((c) => [c.name, c.slug])
);
